@MbokTask_HostAddress = http://localhost:5172

### Health Endpoints

GET {{MbokTask_HostAddress}}/health/
Accept: application/json
###
GET {{MbokTask_HostAddress}}/health/ready/
Accept: application/json
###
GET {{MbokTask_HostAddress}}/health/live/
Accept: application/json
